### ISSUE TITLE
clean up '\r' in some files

### ISSUE THREAD

**Issue by ophilon** [MaxFeoktistov/smallsrv#3]
Hi Max.

2 issues in your interesting project.

1. It's not normal that there are no issues at all, this one fixes it.

2. Me found a weird mix of normal '\n' and windows '\r\n' line terminations:

```
$ find -type f|grep -v '/\.git/'|wc -l
196
$ find -type f|grep -v '/\.git/'|xargs grep -Pl '\r'|wc -l
56
```

If you want, I'll send the 1st PR, to expand the contributor's list :)

**Comment by MaxFeoktistov** [comment]
These sources can be compiled for Linux, Unix-like systems and Windows. Example .bat scripts and .rc files, DJGPP build files must contain \r\n terminators. Yes, the 3 .cpp files that are used to build Linux also contain \r\n, but that's not a big problem. The GCC compiler understands this line terminator well. I'll fix it when these files are edited...
